a = input("Digite algo: ")
print("o tipo primitivo desse valor é ", type(a))
print("É só espaço?", a.isspace())
print("É um número", a.isnumeric())
print("é alfabetico?", a.isalpha())
print("É alfanúmerico?", a.isalnum())
print("Está em maiusculo?", a.isupper())
print("Está em minusculo?", a.islower())
print("Esta capitalizada?", a.istitle())